[build] stop using JDK 1.8
Context: https://github.com/xamarin/xamarin-android/pull/7701#pullrequestreview-1252878695

The latest manifest-merger no longer supports JDK 1.8:

    > Task :compileJava FAILED
    /Users/builder/azdo/_work/1/s/xamarin-android/src/manifestmerger/src/com/xamarin/manifestmerger/Main.java:10: error: cannot access Merger
    import com.android.manifmerger.Merger;
                                ^
    bad class file: /Users/builder/.gradle/caches/modules-2/files-2.1/com.android.tools.build/manifest-merger/30.4.0/f424a0d38608a2c0498453d09534d927d5a091e/manifest-merger-30.4.0.jar(com/android/manifmerger/Merger.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.

We are fully on JDK 11 now, so we can safely stop provisioning and building with JDK 1.8.

This mainly just deletes a lot of code we don't need anymore. :thumbsup: