WIP test builds in parallel
This test currently errors with:

    CSC error CS2012: Cannot open 'C:\src\xamarin-android\bin\TestDebug\temp\ParallelDesignTimeBuild\obj\Debug\UnnamedProject.dll' for writing --
    'The process cannot access the file 'C:\src\xamarin-android\bin\TestDebug\temp\ParallelDesignTimeBuild\obj\Debug\UnnamedProject.dll' because it is being used by another process.'